// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResiduosBackend.Data;

#nullable disable

namespace ResiduosBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601151813_AddCostoFichasResiduo")]
    partial class AddCostoFichasResiduo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ResiduosBackend.Models.AvatarPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("RecursoUnity")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Slot", "Orden");

                    b.ToTable("AvatarParts");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Nombre = "Azul Base",
                            Orden = 0,
                            RecursoUnity = "Blue 2 Base",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 102,
                            Nombre = "Azul Oscuro",
                            Orden = 1,
                            RecursoUnity = "Blue 1 Dark",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 103,
                            Nombre = "Azul Claro",
                            Orden = 2,
                            RecursoUnity = "Blue 3 Light",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 104,
                            Nombre = "Rojo Base",
                            Orden = 3,
                            RecursoUnity = "Red 2 Base",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 105,
                            Nombre = "Rojo Oscuro",
                            Orden = 4,
                            RecursoUnity = "Red 1 Dark",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 106,
                            Nombre = "Rojo Claro",
                            Orden = 5,
                            RecursoUnity = "Red 3 Light",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 107,
                            Nombre = "Verde Base",
                            Orden = 6,
                            RecursoUnity = "Green 2 Base",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 108,
                            Nombre = "Amarillo Base",
                            Orden = 7,
                            RecursoUnity = "Yellow 2 Base",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 109,
                            Nombre = "Morado Base",
                            Orden = 8,
                            RecursoUnity = "Purple 2 Base",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 110,
                            Nombre = "Rosa Base",
                            Orden = 9,
                            RecursoUnity = "Pink 2 Base",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 111,
                            Nombre = "Naranja Base",
                            Orden = 10,
                            RecursoUnity = "Orange 2 Base",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 112,
                            Nombre = "Cian Base",
                            Orden = 11,
                            RecursoUnity = "Cyan 2 Base",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 113,
                            Nombre = "Turquesa Base",
                            Orden = 12,
                            RecursoUnity = "Turquoise 2 Base",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 114,
                            Nombre = "Café Base",
                            Orden = 13,
                            RecursoUnity = "Brown 2 Base",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 115,
                            Nombre = "Crema Base",
                            Orden = 14,
                            RecursoUnity = "Cream 2 Base",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 116,
                            Nombre = "Gris Base",
                            Orden = 15,
                            RecursoUnity = "Grey 2 Base",
                            Slot = "Body"
                        },
                        new
                        {
                            Id = 201,
                            Nombre = "Feliz",
                            Orden = 0,
                            RecursoUnity = "face 1",
                            Slot = "Face"
                        },
                        new
                        {
                            Id = 202,
                            Nombre = "Enojado",
                            Orden = 1,
                            RecursoUnity = "face 2",
                            Slot = "Face"
                        },
                        new
                        {
                            Id = 203,
                            Nombre = "Triste",
                            Orden = 2,
                            RecursoUnity = "face 3",
                            Slot = "Face"
                        },
                        new
                        {
                            Id = 301,
                            Nombre = "Sin sombrero",
                            Orden = 0,
                            RecursoUnity = "",
                            Slot = "Hat"
                        },
                        new
                        {
                            Id = 302,
                            Nombre = "Sombrero de chef",
                            Orden = 1,
                            RecursoUnity = "chef hat",
                            Slot = "Hat"
                        },
                        new
                        {
                            Id = 303,
                            Nombre = "Sombrero de fiesta",
                            Orden = 2,
                            RecursoUnity = "party hat",
                            Slot = "Hat"
                        },
                        new
                        {
                            Id = 304,
                            Nombre = "Sombrero naranja",
                            Orden = 3,
                            RecursoUnity = "orange fedora",
                            Slot = "Hat"
                        },
                        new
                        {
                            Id = 401,
                            Nombre = "PFP Oso",
                            Orden = 0,
                            RecursoUnity = "pfp_bear",
                            Slot = "PFP"
                        },
                        new
                        {
                            Id = 402,
                            Nombre = "PFP Pollo",
                            Orden = 1,
                            RecursoUnity = "pfp_chicken",
                            Slot = "PFP"
                        },
                        new
                        {
                            Id = 403,
                            Nombre = "PFP Koala",
                            Orden = 2,
                            RecursoUnity = "pfp_koala",
                            Slot = "PFP"
                        },
                        new
                        {
                            Id = 404,
                            Nombre = "PFP Suricata",
                            Orden = 3,
                            RecursoUnity = "pfp_meerkat",
                            Slot = "PFP"
                        },
                        new
                        {
                            Id = 405,
                            Nombre = "PFP Panda",
                            Orden = 4,
                            RecursoUnity = "pfp_panda",
                            Slot = "PFP"
                        });
                });

            modelBuilder.Entity("ResiduosBackend.Models.Dispositivo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Dispositivos");
                });

            modelBuilder.Entity("ResiduosBackend.Models.EnciclopediaDesbloqueo", b =>
                {
                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("ResiduoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDesbloqueo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PerfilId", "ResiduoId");

                    b.HasIndex("ResiduoId");

                    b.ToTable("EnciclopediaDesbloqueos");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PerfilId", "ItemId")
                        .IsUnique();

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CostoEstrellas")
                        .HasColumnType("int");

                    b.Property<int>("CostoFichas")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("NivelDesbloqueo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreSprite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Logro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("RequisitoXP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Logros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Alcanza 100 XP acumulada.",
                            ImagenUrl = "logros/reciclador-novato.png",
                            Nombre = "Reciclador Novato",
                            RequisitoXP = 100
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Alcanza 500 XP acumulada.",
                            ImagenUrl = "logros/guardian-planeta.png",
                            Nombre = "Guardian del Planeta",
                            RequisitoXP = 500
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Alcanza 1000 XP acumulada.",
                            ImagenUrl = "logros/maestro-reciclaje.png",
                            Nombre = "Maestro del Reciclaje",
                            RequisitoXP = 1000
                        });
                });

            modelBuilder.Entity("ResiduosBackend.Models.PartidaMetrica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaPartida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("PuntuacionObtenida")
                        .HasColumnType("int");

                    b.Property<int>("ResiduosClasificadosCorrectamente")
                        .HasColumnType("int");

                    b.Property<int>("ResiduosInorganicosClasificados")
                        .HasColumnType("int");

                    b.Property<int>("ResiduosOrganicosClasificados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("PartidaMetricas");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BodyPartId")
                        .HasColumnType("int");

                    b.Property<string>("DispositivoId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<int>("EstrellaSostenibilidad")
                        .HasColumnType("int");

                    b.Property<int>("Experiencia")
                        .HasColumnType("int");

                    b.Property<int>("FacePartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("HatPartId")
                        .HasColumnType("int");

                    b.Property<int>("Monedas")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ProfilePictureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BodyPartId");

                    b.HasIndex("DispositivoId");

                    b.HasIndex("FacePartId");

                    b.HasIndex("HatPartId");

                    b.HasIndex("ProfilePictureId");

                    b.ToTable("Perfiles");
                });

            modelBuilder.Entity("ResiduosBackend.Models.PerfilLogro", b =>
                {
                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("LogroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaObtencion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PerfilId", "LogroId");

                    b.HasIndex("LogroId");

                    b.ToTable("PerfilLogros");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Residuo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CostoFichas")
                        .HasColumnType("int");

                    b.Property<string>("DatoCurioso")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("DescripcionParaNinos")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreSprite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Subcategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Residuos");
                });

            modelBuilder.Entity("ResiduosBackend.Models.EnciclopediaDesbloqueo", b =>
                {
                    b.HasOne("ResiduosBackend.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiduosBackend.Models.Residuo", "Residuo")
                        .WithMany("Desbloqueos")
                        .HasForeignKey("ResiduoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Residuo");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Inventario", b =>
                {
                    b.HasOne("ResiduosBackend.Models.Item", "Item")
                        .WithMany("Inventarios")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiduosBackend.Models.Perfil", "Perfil")
                        .WithMany("Inventarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("ResiduosBackend.Models.PartidaMetrica", b =>
                {
                    b.HasOne("ResiduosBackend.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Perfil", b =>
                {
                    b.HasOne("ResiduosBackend.Models.AvatarPart", "BodyPart")
                        .WithMany()
                        .HasForeignKey("BodyPartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResiduosBackend.Models.Dispositivo", "Dispositivo")
                        .WithMany("Perfiles")
                        .HasForeignKey("DispositivoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiduosBackend.Models.AvatarPart", "FacePart")
                        .WithMany()
                        .HasForeignKey("FacePartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResiduosBackend.Models.AvatarPart", "HatPart")
                        .WithMany()
                        .HasForeignKey("HatPartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResiduosBackend.Models.AvatarPart", "ProfilePicturePart")
                        .WithMany()
                        .HasForeignKey("ProfilePictureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BodyPart");

                    b.Navigation("Dispositivo");

                    b.Navigation("FacePart");

                    b.Navigation("HatPart");

                    b.Navigation("ProfilePicturePart");
                });

            modelBuilder.Entity("ResiduosBackend.Models.PerfilLogro", b =>
                {
                    b.HasOne("ResiduosBackend.Models.Logro", "Logro")
                        .WithMany("PerfilesLogro")
                        .HasForeignKey("LogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiduosBackend.Models.Perfil", "Perfil")
                        .WithMany("LogrosDesbloqueados")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logro");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Dispositivo", b =>
                {
                    b.Navigation("Perfiles");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Item", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Logro", b =>
                {
                    b.Navigation("PerfilesLogro");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Perfil", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("LogrosDesbloqueados");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Residuo", b =>
                {
                    b.Navigation("Desbloqueos");
                });
#pragma warning restore 612, 618
        }
    }
}
