// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResiduosBackend.Data;

#nullable disable

namespace ResiduosBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427180106_SistemaLogros")]
    partial class SistemaLogros
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ResiduosBackend.Models.EnciclopediaDesbloqueo", b =>
                {
                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("ResiduoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaDesbloqueo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PerfilId", "ResiduoId");

                    b.HasIndex("ResiduoId");

                    b.ToTable("EnciclopediaDesbloqueos");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PerfilId", "ItemId")
                        .IsUnique();

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CostoEstrellas")
                        .HasColumnType("int");

                    b.Property<int>("CostoFichas")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("NivelDesbloqueo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreSprite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Logro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("RequisitoXP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Logros");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Alcanza 100 XP acumulada.",
                            ImagenUrl = "logros/reciclador-novato.png",
                            Nombre = "Reciclador Novato",
                            RequisitoXP = 100
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Alcanza 500 XP acumulada.",
                            ImagenUrl = "logros/guardian-planeta.png",
                            Nombre = "Guardian del Planeta",
                            RequisitoXP = 500
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Alcanza 1000 XP acumulada.",
                            ImagenUrl = "logros/maestro-reciclaje.png",
                            Nombre = "Maestro del Reciclaje",
                            RequisitoXP = 1000
                        });
                });

            modelBuilder.Entity("ResiduosBackend.Models.PartidaMetrica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaPartida")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("PuntuacionObtenida")
                        .HasColumnType("int");

                    b.Property<int>("ResiduosClasificadosCorrectamente")
                        .HasColumnType("int");

                    b.Property<int>("ResiduosInorganicosClasificados")
                        .HasColumnType("int");

                    b.Property<int>("ResiduosOrganicosClasificados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("PartidaMetricas");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstrellaSostenibilidad")
                        .HasColumnType("int");

                    b.Property<int>("Experiencia")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Monedas")
                        .HasColumnType("int");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Perfiles");
                });

            modelBuilder.Entity("ResiduosBackend.Models.PerfilLogro", b =>
                {
                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("LogroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaObtencion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("PerfilId", "LogroId");

                    b.HasIndex("LogroId");

                    b.ToTable("PerfilLogros");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Residuo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DatoCurioso")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("DescripcionParaNinos")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NombreSprite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Subcategoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Residuos");
                });

            modelBuilder.Entity("ResiduosBackend.Models.EnciclopediaDesbloqueo", b =>
                {
                    b.HasOne("ResiduosBackend.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiduosBackend.Models.Residuo", "Residuo")
                        .WithMany("Desbloqueos")
                        .HasForeignKey("ResiduoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Residuo");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Inventario", b =>
                {
                    b.HasOne("ResiduosBackend.Models.Item", "Item")
                        .WithMany("Inventarios")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiduosBackend.Models.Perfil", "Perfil")
                        .WithMany("Inventarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("ResiduosBackend.Models.PartidaMetrica", b =>
                {
                    b.HasOne("ResiduosBackend.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("ResiduosBackend.Models.PerfilLogro", b =>
                {
                    b.HasOne("ResiduosBackend.Models.Logro", "Logro")
                        .WithMany("PerfilesLogro")
                        .HasForeignKey("LogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResiduosBackend.Models.Perfil", "Perfil")
                        .WithMany("LogrosDesbloqueados")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logro");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Item", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Logro", b =>
                {
                    b.Navigation("PerfilesLogro");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Perfil", b =>
                {
                    b.Navigation("Inventarios");

                    b.Navigation("LogrosDesbloqueados");
                });

            modelBuilder.Entity("ResiduosBackend.Models.Residuo", b =>
                {
                    b.Navigation("Desbloqueos");
                });
#pragma warning restore 612, 618
        }
    }
}
